### ISSUE TITLE
warning " > @moia-oss/eslint-prettier-typescript-config@0.11.41" has incorrect peer dependency "eslint@^8.4.1".

### ISSUE THREAD

**Issue by 3oris** [moia-oss/eslint-prettier-typescript-config#355]
When using the `eslint-prettier-typescript-config` module, `yarn install` issues this warning. I looked at the `package.json` and wonder if it is because of the difference of dev and peer dependencies:

```
  "devDependencies": {
    "eslint": "^8.17.0",
    "prettier": "^2.5.1",
    "typescript": "^4.7.3"
  },
  "peerDependencies": {
    "eslint": "^8.4.1",
    "prettier": "^2.5.1",
    "typescript": "^4.5.2"
  },
  ```
  
  cc @sanderdrummer

**Comment by sanderdrummer** [comment]
mh the ^ should actually allow all minor version bumps.
But we can update the peer dependencies. 👍🏼
